language: python
python:
  - "3.5"
cache: pip

before_script:
  - echo TRAVIS_BRANCH=${TRAVIS_BRANCH}
  - echo TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
  - echo TRAVIS_TAG=${TRAVIS_TAG}
  - echo MTB_PR=${MTB_PR}
  - echo MTB_MERGE_MASTER=${MTB_MERGE_MASTER}

before_install:
  # figlet
  - sudo apt-get install -y figlet
  # awscli, pytest
  - pip install -r requirements.txt
  # packer
  - sudo apt-get install -y unzip
  - sudo mkdir tmp
  - cd tmp
  - sudo curl -L -o packer.zip https://releases.hashicorp.com/packer/1.0.0/packer_1.0.0_linux_amd64.zip
  - sudo unzip packer.zip
  - sudo mv packer /usr/local/
  - export PATH="$PATH:/usr/local/packer"
  - packer --version
  - cd /home/travis/build/daisuke-awaji/aws/

script:
  # Cloudformation test
  - pytest ./cloudformation/tests/test.py

  #  __  __    _    ____   ____ _____ ____
  # |  \/  |  / \  |  _ \ / ___| ____|  _ \
  # | |\/| | / _ \ | |_) | |  _|  _| | | | |
  # | |  | |/ ___ \|  _ <| |_| | |___| |_| |
  # |_|  |_/_/   \_\_| \_\\____|_____|____/

  # Master branch was pushed or marged by develop branches
  - |
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      figlet Master Branch Deploy;

      ENV=prod;
      echo "[INFO] Master branch was pushed or marged by feature branches";
      echo "[BUILD] Packer build.";


      packer build ./middleware/template.json >> out.log;
      cat out.log;
      AMIID=`cat out.log | tail -2 | head -2 | awk 'match($0, /ami-.*/) { print substr($0, RSTART, RLENGTH) }'`;
      echo ${AMIID};


      echo "[BUILD] Deploy Stack...";
      aws cloudformation deploy \
          --template-file=./cloudformation/template.yaml \
          --stack-name ${ENV} \
          --parameter-overrides Environment=${ENV} \
          --parameter-overrides WebInstanceAMI=${AMIID} \
          --capabilities CAPABILITY_IAM \
          --region ${AWS_REGION};
    fi

  # Develop branch was pushed or marged by feature branches
  - |
    if [ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      figlet Develop Branch Deploy;

      ENV=dev;
      echo "[INFO] Develop branch was pushed or marged by feature branches";
      echo "[BUILD] Packer build. Create AMI.";


      packer build ./middleware/template.json >> out.log;
      cat out.log;
      AMIID=`cat out.log | tail -2 | head -2 | awk 'match($0, /ami-.*/) { print substr($0, RSTART, RLENGTH) }'`;
      echo ${AMIID};


      echo "[BUILD] Deploy Stack...";
      aws cloudformation deploy \
          --template-file=./cloudformation/template.yaml \
          --stack-name ${ENV} \
          --parameter-overrides Environment=${ENV} \
          --parameter-overrides WebInstanceAMI=${AMIID} \
          --capabilities CAPABILITY_IAM \
          --region ${AWS_REGION};
    fi

  #  ____  _   _ _     _       ____  _____ ___  _   _ _____ ____ _____ ____
  # |  _ \| | | | |   | |     |  _ \| ____/ _ \| | | | ____/ ___|_   _/ ___|
  # | |_) | | | | |   | |     | |_) |  _|| | | | | | |  _| \___ \ | | \___ \
  # |  __/| |_| | |___| |___  |  _ <| |__| |_| | |_| | |___ ___) || |  ___) |
  # |_|    \___/|_____|_____| |_| \_\_____\__\_\\___/|_____|____/ |_| |____/

  # Pull Requests was created for develop to master
  - |
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      figlet Master Pull Request Build;

      ENV=prod;
      echo "[INFO] Pull Request was created";
      echo "[BUILD] Create Stack...";
      DATE=$(date +"%Y%m%d%H%M%S");

      aws cloudformation create-change-set \
          --template-body file://cloudformation/template.yaml \
          --change-set-name "change-set-${DATE}" \
          --stack-name ${ENV} \
          --parameters ParameterKey=Environment,ParameterValue=${ENV} \
          --capabilities CAPABILITY_IAM \
          --region ${AWS_REGION};
    fi

  # Pull Requests was created for feature to develop
  - |
    if [ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      figlet Develop Pull Request Build;

      ENV=dev;
      echo "[INFO] Pull Request was created";
      echo "[BUILD] Create Stack...";
      DATE=$(date +"%Y%m%d%H%M%S");

      aws cloudformation create-change-set \
          --template-body file://cloudformation/template.yaml \
          --change-set-name "change-set-${DATE}" \
          --stack-name ${ENV} \
          --parameters ParameterKey=Environment,ParameterValue=${ENV} \
          --capabilities CAPABILITY_IAM \
          --region ${AWS_REGION};
    fi


  #   ___  _   _ _  __   __  ____  _   _ ____  _   _ _____ ____
  #  / _ \| \ | | | \ \ / / |  _ \| | | / ___|| | | | ____|  _ \
  # | | | |  \| | |  \ V /  | |_) | | | \___ \| |_| |  _| | | | |
  # | |_| | |\  | |___| |   |  __/| |_| |___) |  _  | |___| |_| |
  #  \___/|_| \_|_____|_|   |_|    \___/|____/|_| |_|_____|____/

  # Feature branch was pushed
  - |
    if [ "$TRAVIS_BRANCH" != "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      echo "[INFO] Only Pushed";
      echo "[INFO] Nothing to do";
      echo "[INFO] Feature branch was pushed";
      echo "[INFO] Nothing to do anything";
    fi

after_success:
  - coveralls
